// playground/vue/src/App.vue
<script setup lang="ts">
import {
  isClipboardReadSupported,
  isClipboardSupported,
} from '@ngockhoi96/ctc'
import { useCopyToClipboard } from '@ngockhoi96/ctc-vue'
import { onMounted, ref } from 'vue'

const text = ref('Hello from @ngockhoi96/ctc-vue')
const { copy, copied, error } = useCopyToClipboard()

type Detection = {
  clipboardApi: boolean | null
  clipboardRead: boolean | null
  secureContext: boolean | null
}

const detection = ref<Detection>({
  clipboardApi: null,
  clipboardRead: null,
  secureContext: null,
})

onMounted(() => {
  detection.value.clipboardApi = isClipboardSupported()
  detection.value.clipboardRead = isClipboardReadSupported()
  detection.value.secureContext = window.isSecureContext
})

const detectionRows = [
  { key: 'clipboardApi' as const, label: 'isClipboardSupported()' },
  { key: 'clipboardRead' as const, label: 'isClipboardReadSupported()' },
  { key: 'secureContext' as const, label: 'window.isSecureContext' },
]
</script>

<template>
  <div class="container">
    <h1>@ngockhoi96/ctc -- Vue Playground</h1>

    <section>
      <h2>Copy to Clipboard</h2>
      <input v-model="text" type="text" />
      <button @click="copy(text)">Copy</button>
      <div class="feedback">
        <span v-if="copied" class="copied">Copied!</span>
        <span v-else-if="error !== null" class="error">Error: {{ error?.code }}</span>
      </div>
    </section>

    <section>
      <h2>Secure Context</h2>
      <span
        v-if="detection.secureContext !== null"
        class="badge"
        :class="detection.secureContext ? 'secure' : 'insecure'"
      >
        {{ detection.secureContext ? 'Secure Context' : 'Insecure Context' }}
      </span>
    </section>

    <section>
      <h2>Detection Panel</h2>
      <table>
        <thead>
          <tr>
            <th>Function</th>
            <th>Result</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in detectionRows" :key="row.key">
            <td>{{ row.label }}</td>
            <td>{{ detection[row.key] === null ? 'checking...' : String(detection[row.key]) }}</td>
          </tr>
        </tbody>
      </table>
    </section>
  </div>
</template>

<style scoped>
.container {
  font-family: system-ui, sans-serif;
  max-width: 600px;
  margin: 2rem auto;
  padding: 0 1rem;
}
h1 { font-size: 1.25rem; margin-bottom: 1.5rem; }
section { margin-bottom: 1.5rem; }
h2 { font-size: 1rem; margin-bottom: 0.5rem; }
input {
  border: 1px solid #ccc;
  padding: 0.4rem 0.6rem;
  border-radius: 4px;
  width: 100%;
  box-sizing: border-box;
  margin-bottom: 0.5rem;
}
button {
  padding: 0.4rem 1rem;
  border-radius: 4px;
  border: 1px solid #888;
  cursor: pointer;
  background: #f4f4f4;
}
button:hover { background: #e0e0e0; }
.feedback { margin-top: 0.4rem; font-size: 0.875rem; min-height: 1.25em; }
.copied { color: green; }
.error { color: red; }
.badge {
  display: inline-block;
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: bold;
}
.secure { background: #d4edda; color: #155724; }
.insecure { background: #f8d7da; color: #721c24; }
table { border-collapse: collapse; width: 100%; font-size: 0.875rem; }
th, td { text-align: left; padding: 0.3rem 0.5rem; border-bottom: 1px solid #eee; }
th { background: #f9f9f9; }
</style>

// playground/react/src/App.tsx
import { isClipboardReadSupported, isClipboardSupported } from '@ngockhoi96/ctc'
import { useCopyToClipboard } from '@ngockhoi96/ctc-react'
import { useEffect, useState } from 'react'

type DetectionState = {
	clipboardApi: boolean | null
	secureContext: boolean | null
	clipboardRead: boolean | null
}

export function App() {
	const [text, setText] = useState('Hello from @ngockhoi96/ctc-react')
	const { copy, copied, error } = useCopyToClipboard()
	const [detection, setDetection] = useState<DetectionState>({
		clipboardApi: null,
		secureContext: null,
		clipboardRead: null,
	})

	useEffect(() => {
		const clipboardApi = isClipboardSupported()
		const secureContext = window.isSecureContext
		const clipboardRead = isClipboardReadSupported()
		setDetection({ clipboardApi, secureContext, clipboardRead })
	}, [])

	const secure = detection.secureContext

	return (
		<div
			style={{
				fontFamily: 'system-ui, sans-serif',
				maxWidth: 600,
				margin: '2rem auto',
				padding: '0 1rem',
			}}
		>
			<h1 style={{ fontSize: '1.25rem', marginBottom: '1.5rem' }}>
				@ngockhoi96/ctc -- React Playground
			</h1>

			<section style={{ marginBottom: '1.5rem' }}>
				<h2 style={{ fontSize: '1rem', marginBottom: '0.5rem' }}>
					Copy to Clipboard
				</h2>
				<input
					type="text"
					value={text}
					onChange={(e) => setText(e.target.value)}
					style={{
						border: '1px solid #ccc',
						padding: '0.4rem 0.6rem',
						borderRadius: 4,
						width: '100%',
						boxSizing: 'border-box',
						marginBottom: '0.5rem',
					}}
				/>
				<button
					type="button"
					onClick={() => copy(text)}
					style={{
						padding: '0.4rem 1rem',
						borderRadius: 4,
						border: '1px solid #888',
						cursor: 'pointer',
						background: '#f4f4f4',
					}}
				>
					Copy
				</button>
				<div
					style={{
						marginTop: '0.4rem',
						fontSize: '0.875rem',
						minHeight: '1.25em',
					}}
				>
					{copied && <span style={{ color: 'green' }}>Copied!</span>}
					{!copied && error !== null && (
						<span style={{ color: 'red' }}>Error: {error.code}</span>
					)}
				</div>
			</section>

			<section style={{ marginBottom: '1.5rem' }}>
				<h2 style={{ fontSize: '1rem', marginBottom: '0.5rem' }}>
					Secure Context
				</h2>
				{secure !== null && (
					<span
						style={{
							display: 'inline-block',
							padding: '0.2rem 0.5rem',
							borderRadius: 4,
							fontSize: '0.75rem',
							fontWeight: 'bold',
							background: secure ? '#d4edda' : '#f8d7da',
							color: secure ? '#155724' : '#721c24',
						}}
					>
						{secure ? 'Secure Context' : 'Insecure Context'}
					</span>
				)}
			</section>

			<section>
				<h2 style={{ fontSize: '1rem', marginBottom: '0.5rem' }}>
					Detection Panel
				</h2>
				<table
					style={{
						borderCollapse: 'collapse',
						width: '100%',
						fontSize: '0.875rem',
					}}
				>
					<thead>
						<tr>
							<th
								style={{
									textAlign: 'left',
									padding: '0.3rem 0.5rem',
									background: '#f9f9f9',
									borderBottom: '1px solid #eee',
								}}
							>
								Function
							</th>
							<th
								style={{
									textAlign: 'left',
									padding: '0.3rem 0.5rem',
									background: '#f9f9f9',
									borderBottom: '1px solid #eee',
								}}
							>
								Result
							</th>
						</tr>
					</thead>
					<tbody>
						{[
							{
								label: 'isClipboardSupported()',
								value: detection.clipboardApi,
							},
							{
								label: 'isClipboardReadSupported()',
								value: detection.clipboardRead,
							},
							{
								label: 'window.isSecureContext',
								value: detection.secureContext,
							},
						].map(({ label, value }) => (
							<tr key={label}>
								<td
									style={{
										padding: '0.3rem 0.5rem',
										borderBottom: '1px solid #eee',
									}}
								>
									{label}
								</td>
								<td
									style={{
										padding: '0.3rem 0.5rem',
										borderBottom: '1px solid #eee',
									}}
								>
									{value === null ? 'checking...' : String(value)}
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</section>
		</div>
	)
}
